#include <stdio.h>
#include <time.h>

// PROBLEM STATEMENT:
// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million,
// find the sum of the even-valued terms.


int main() {
    int fib1 = 1;
    int fib2 = 2;
    int fib_next = 0;
    int res = 0;
    time_t start, end;
    double cpu_time_used = 0.0;

    start = clock();
    while(fib_next < 4000000) {
        if ((fib2 & 1) == 0) // if ((fib2 % 2) == 0))
            res += fib2;
        fib_next = fib1 + fib2;
        fib1 = fib2;
        fib2 = fib_next;
    }
    end = clock();
    cpu_time_used = (double)(end - start) / CLOCKS_PER_SEC;
    printf("RESULT: %d\nRUNTIME: %f\n", res, cpu_time_used);

    return 0;
}
